spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filmzoo
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

film:
  api-key: 3UmCPVVHQ97U4d2tnJbzbo:7EDNehJEjws1WxP4Irhvsf